name = "CompatEntryUtilities"
uuid = "8be7a408-1a4a-465c-8be3-3898d13eb8a5"
authors = ["Dilum Aluthge", "contributors"]
version = "2.0.6"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.6"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test"]
